
SELECT CAST(REP_DT AS DATE)
FROM XDW_V.NODE_HELTH_TECHSCORE_TWC AS DB
WHERE XDW_REC_STS_CD = 'A'
AND REP_DT  = DATE'2017-06-21'
AND BLG_STN_ID IS NULL
AND TM_KMA_NAME NOT IN ('Honolulu')
AND SUBSTR(DB.Fibr_Node,1,1)=DB.Billing_Hub
OR SUBSTR(DB.Fibr_Node,1,2)=DB.Billing_Hub
