SHOW TABLE XBIWrk.LdSpPLDMgrSysTechScrcrdPriNd002;


CREATE MULTISET TABLE XBIWrk.LdSpPLDMgrSysTechScrcrdConslPriNd001 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 
      CalDt DATE FORMAT 'yyyy-mm-dd',
      FibrNode VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      AsscId BIGINT,
      BlgStnId INTEGER,
      BlgStnLvl1Cd VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      BlgStnLvl2Cd VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      VldFromDt TIMESTAMP(0),
      VldToDt TIMESTAMP(0),
      NodeScore DECIMAL(15,1),
      TotDvcCnt DECIMAL(10,4)
	  )
PRIMARY INDEX LdSpPLDMgrSysTechScrcrdConslPriNd001PI  ( BlgStnLvl1Cd ,BlgStnLvl2Cd );
COLLECT STATISTICS COLUMN  ( BlgStnLvl1Cd ,BlgStnLvl2Cd ) ON XBIWrk.LdSpPLDMgrSysTechScrcrdConslPriNd001	;

REPLACE VIEW  XBIWRKv.LdSpPLDMgrSysTechScrcrdConslPriNd001 AS LOCKING ROW FOR ACCESS SELECT * FROM  XBIWRK.LdSpPLDMgrSysTechScrcrdConslPriNd001;


CREATE MULTISET TABLE XBIWrk.LdSpPLDMgrSysTechScrcrdConslSecNd001 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 
      BlgStnLvl1Cd VARCHAR(16) CHARACTER SET LATIN NOT CASESPECIFIC,
      BlgStnLvl2Cd VARCHAR(16) CHARACTER SET LATIN NOT CASESPECIFIC,
      SysPrin VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC
	  )
PRIMARY INDEX LdSpPLDMgrSysTechScrcrdConslSecNd001PI  ( BlgStnLvl1Cd ,BlgStnLvl2Cd );
COLLECT STATISTICS COLUMN  ( BlgStnLvl1Cd ,BlgStnLvl2Cd ) ON XBIWrk.LdSpPLDMgrSysTechScrcrdConslSecNd001	;

REPLACE VIEW  XBIWRKv.LdSpPLDMgrSysTechScrcrdConslSecNd001 AS LOCKING ROW FOR ACCESS SELECT * FROM  XBIWRK.LdSpPLDMgrSysTechScrcrdConslSecNd001;




CREATE MULTISET TABLE XBITbls.PLDMgrSysTechScrcrdConslPriNd ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DimFsclMthSk INTEGER NOT NULL DEFAULT -1 ,
      MgrHrNum VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      TechHrNum VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      NodeCnt INTEGER,
      PrimMthGreenNdPerc DECIMAL(10,4),
      ExecStatId BIGINT,
      SnapDttm TIMESTAMP(6),
      InsDttm TIMESTAMP(6),
      RecOpInd CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC

	  )
PRIMARY INDEX PLDMgrSysTechScrcrdConslPriNdPI ( DimFsclMthSk ,MgrHrNum ,TechHrNum );
COLLECT STATISTICS COLUMN ( DimFsclMthSk ,MgrHrNum ,TechHrNum ) ON XBITbls.PLDMgrSysTechScrcrdConslPriNd	;


--View
REPLACE VIEW XBITblsV.PLDMgrSysTechScrcrdConslPriNd AS LOCKING ROW FOR ACCESS SELECT * FROM XBITbls.PLDMgrSysTechScrcrdConslPriNd ;




CREATE MULTISET TABLE XBITbls.PLDSupSysTechScrcrdConslSecNd ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DimFsclMthSk	INTEGER,
SupHrNum	VARCHAR(100),
TechHrNum	VARCHAR(255),
secTotalScrdNodes	INTEGER,
secMthGreenNdPerc	DECIMAL,
ExecStatId	BIGINT,
SnapDttm	TIMESTAMP,
InsDttm	TIMESTAMP,
RecOpInd	CHAR(1)

	  )
PRIMARY INDEX PLDSupSysTechScrcrdConslSecNdPI ( DimFsclMthSk,SupHrNum,TechHrNum);
COLLECT STATISTICS COLUMN  ( DimFsclMthSk,SupHrNum,TechHrNum) ON XBITbls.PLDSupSysTechScrcrdConslSecNd	;


--View
REPLACE VIEW XBITblsV.PLDSupSysTechScrcrdConslSecNd AS LOCKING ROW FOR ACCESS SELECT * FROM XBITbls.PLDSupSysTechScrcrdConslSecNd ;


CREATE MULTISET TABLE XBIWrk.LdSpPLDSupSysTechScrcrdConslSecNd001 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 
      BlgStnLvl1Cd VARCHAR(16) CHARACTER SET LATIN NOT CASESPECIFIC,
      BlgStnLvl2Cd VARCHAR(16) CHARACTER SET LATIN NOT CASESPECIFIC,
      SysPrin VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC
	  )
PRIMARY INDEX LdSpPLDSupSysTechScrcrdConslSecNd001PI  ( BlgStnLvl1Cd ,BlgStnLvl2Cd );
COLLECT STATISTICS COLUMN  ( BlgStnLvl1Cd ,BlgStnLvl2Cd ) ON XBIWrk.LdSpPLDSupSysTechScrcrdSecNd001	;

REPLACE VIEW  XBIWRKv.LdSpPLDSupSysTechScrcrdConslSecNd001 AS LOCKING ROW FOR ACCESS SELECT * FROM  XBIWRK.LdSpPLDSupSysTechScrcrdConslSecNd001;

CREATE MULTISET TABLE XBIWrk.LdSpPLDSupSysTechScrcrdConslSecNd002 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 
      CalDt DATE FORMAT 'yyyy-mm-dd',
      FibrNode VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      AsscId BIGINT,
      BlgStnId INTEGER,
      BlgStnLvl1Cd VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      BlgStnLvl2Cd VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      VldFromDt TIMESTAMP(0),
      VldToDt TIMESTAMP(0),
      NodeScore DECIMAL(15,1),
      TotDvcCnt DECIMAL(10,4)
	  )
PRIMARY INDEX LdSpPLDSupSysTechScrcrdConslSecNd002PI  ( CalDt ,FibrNode ,AsscId ,BlgStnId ,VldFromDt );
COLLECT STATISTICS COLUMN  ( BlgStnLvl1Cd ,BlgStnLvl2Cd ) ON XBIWrk.LdSpPLDSupSysTechScrcrdConslSecNd002


REPLACE VIEW  XBIWRKv.LdSpPLDSupSysTechScrcrdConslSecNd002 AS LOCKING ROW FOR ACCESS SELECT * FROM  XBIWRK.LdSpPLDSupSysTechScrcrdConslSecNd002;

CREATE MULTISET TABLE XBIWRK.LdSpPLDSupSysTechScrcrdConslSecNd003 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 
      CalDt DATE FORMAT 'yyyy-mm-dd',
      AsscId BIGINT,
      KmaId BIGINT,
      FibrNode VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      NodeScore DECIMAL(15,1),
      TotDvcCnt DECIMAL(10,4)
	  )
PRIMARY INDEX LdSpPLDSupSysTechScrcrdConslSecNd003 ( CalDt ,AsscId ,KmaId ,FibrNode );
COLLECT STATISTICS COLUMN  ( CalDt ,AsscId ,KmaId ,FibrNode ) ON XBIWrk.LdSpPLDSupSysTechScrcrdConslSecNd003	;

REPLACE VIEW  XBIWRKv.LdSpPLDSupSysTechScrcrdConslSecNd003 AS LOCKING ROW FOR ACCESS SELECT * FROM  XBIWRK.LdSpPLDSupSysTechScrcrdConslSecNd003;

CREATE MULTISET TABLE XBIWRK.LdSpPLDSupSysTechScrcrdConslSecNd002 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
	 
        CalDt DATE FORMAT 'yyyy-mm-dd',
      FibrNode VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      AsscId BIGINT,
      BlgStnId INTEGER,
      BlgStnLvl1Cd VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      BlgStnLvl2Cd VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      VldFromDt TIMESTAMP(0),
      VldToDt TIMESTAMP(0),
      NodeScore DECIMAL(15,1),
      TotDvcCnt DECIMAL(10,4)
	  )
PRIMARY INDEX LdSpPLDSupSysTechScrcrdConslSecNd002( CalDt ,FibrNode ,AsscId ,BlgStnId ,VldFromDt );
COLLECT STATISTICS COLUMN ( CalDt ,FibrNode ,AsscId ,BlgStnId ,VldFromDt )ON XBIWrk.LdSpPLDSupSysTechScrcrdConslSecNd002	;

SHOW TABLE xbitbls.
